// <auto-generated/>
            using System.Reflection;
            [assembly: AssemblyMetadataAttribute("githash","0e54d8c568c30066ac96ea231a3fbb86a2691462")]
            namespace System {
                internal static class AssemblyVersionInformation {
                    internal const System.String AssemblyMetadata_githash = "0e54d8c568c30066ac96ea231a3fbb86a2691462";
                }
            }
            