// <auto-generated/>
            using System.Reflection;
            [assembly: AssemblyMetadataAttribute("githash","02fb2ecf87776e995305d48019fdd89e29f478e6")]
            namespace System {
                internal static class AssemblyVersionInformation {
                    internal const System.String AssemblyMetadata_githash = "02fb2ecf87776e995305d48019fdd89e29f478e6";
                }
            }
            