// <auto-generated/>
            using System.Reflection;
            [assembly: AssemblyMetadataAttribute("githash","31fd699076fb0c88f0bee74ed639fc85fdf2c633")]
            namespace System {
                internal static class AssemblyVersionInformation {
                    internal const System.String AssemblyMetadata_githash = "31fd699076fb0c88f0bee74ed639fc85fdf2c633";
                }
            }
            